// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MetalSandbox",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "MetalSandbox",
            targets: ["AppModule"],
            bundleIdentifier: "akira.nakano.test.com",
            teamIdentifier: "P6Y37NCDAQ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .boat),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Losiowaty/PlaygroundTester", "0.3.1"..<"1.0.0"),
        .package(url: "https://github.com/Swinject/Swinject", "2.9.1"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "PlaygroundTester", package: "PlaygroundTester"),
                .product(name: "Swinject", package: "Swinject")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
